module.exports = [
  {
    id: 1,
    userName: "itsFiras",
    firstName: "Firas",
    lastName: "Kingsdom",
    favNumber: 932325,
    isActive: true,
  },
  {
    id: 2,
    userName: "Mdkoe",
    firstName: "AABS",
    lastName: "MORER",
    favNumber: 345,
    isActive: false,
  },
  {
    id: 3,
    userName: "itSRBSSS",
    firstName: "MBC",
    lastName: "SAUDI",
    favNumber: 7,
    isActive: true,
  },
  {
    id: 4,
    userName: "tunsiano",
    firstName: "notAlmofot",
    lastName: "Aloito",
    favNumber: 392100,
    isActive: false,
  },
  {
    id: 5,
    userName: "erbb",
    firstName: "stbrsrbtbs",
    lastName: "ssryd",
    favNumber: 23423,
    isActive: true,
  },
  {
    id: 6,
    userName: "esrhbhrsth",
    firstName: "sbdb",
    lastName: "sdbg",
    favNumber: 232,
    isActive: true,
  },
  {
    id: 7,
    userName: "tunsiano",
    firstName: "notAlmofot",
    lastName: "Aloito",
    favNumber: 346346,
    isActive: true,
  },
  {
    id: 8,
    userName: "tunsiano",
    firstName: "notAlmofot",
    lastName: "Aloito",
    favNumber: 234234,
    isActive: true,
  },
  {
    id: 9,
    userName: "ervesrjtvrev",
    firstName: "erverstjrysv",
    lastName: "srtnryj",
    favNumber: 243242,
    isActive: false,
  },
  {
    id: 10,
    userName: "tunsiwgerheano",
    firstName: "sdvsdv",
    lastName: "sthrtshtrh",
    favNumber: 7675464,
    isActive: true,
  },
];
